/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.88
 * Generated at: 2023-05-31 06:52:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("<script\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("	integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>회원가입</title>\n");
      out.write("</head>\n");
      out.write("<body\n");
      out.write("	style=\"background-image: url('/image/배경화면.png'); background-repeat: no-repeat; background-size: cover;\">\n");
      out.write("	<br>\n");
      out.write("	<div align=\"center\" style=\"width: 350px; height: 500px; border: 1px solid; margin: 100px auto; background-color: white; border-radius: 30px;\"  >\n");
      out.write("	<h1 style=\"margin: 20px auto;\">버니즈 가입</h1>\n");
      out.write("		<form action=\"/mem/register\" method=\"post\">\n");
      out.write("			<div class=\"input-group mb-3\" style=\"width: 300px;\">\n");
      out.write("				<span class=\"input-group-text\" id=\"inputGroup-sizing-default\" style=\"margin-top: 20px;\">아이디</span>\n");
      out.write("				<input type=\"text\" name=\"id\" class=\"form-control\"\n");
      out.write("					aria-label=\"Sizing example input\"\n");
      out.write("					aria-describedby=\"inputGroup-sizing-default\"\n");
      out.write("					placeholder=\"아이디를 입력해주세요.\" style=\"margin-top: 20px;\">\n");
      out.write("			</div>\n");
      out.write("			<br>\n");
      out.write("			<div class=\"input-group mb-3\" style=\"width: 300px;\">\n");
      out.write("				<span class=\"input-group-text\" id=\"inputGroup-sizing-default\">비밀번호</span>\n");
      out.write("				<input type=\"password\" name=\"password\" class=\"form-control\"\n");
      out.write("					aria-label=\"Sizing example input\"\n");
      out.write("					aria-describedby=\"inputGroup-sizing-default\"\n");
      out.write("					placeholder=\"비밀번호를 입력해주세요.\">\n");
      out.write("			</div>\n");
      out.write("			<br>\n");
      out.write("			<div class=\"input-group mb-3\" style=\"width: 300px;\">\n");
      out.write("				<span class=\"input-group-text\" id=\"inputGroup-sizing-default\">전화번호</span>\n");
      out.write("				<input type=\"text\" name=\"phone\" class=\"form-control\"\n");
      out.write("					aria-label=\"Sizing example input\"\n");
      out.write("					aria-describedby=\"inputGroup-sizing-default\"\n");
      out.write("					placeholder=\"ex) 010-1234-5678\">\n");
      out.write("			</div>\n");
      out.write("			<br>\n");
      out.write("			<div class=\"input-group mb-3\" style=\"width: 300px;\">\n");
      out.write("				<span class=\"input-group-text\" id=\"inputGroup-sizing-default\">생년월일</span>\n");
      out.write("				<input type=\"text\" name=\"birth\" class=\"form-control\"\n");
      out.write("					aria-label=\"Sizing example input\"\n");
      out.write("					aria-describedby=\"inputGroup-sizing-default\"\n");
      out.write("					placeholder=\"ex) 20030530\">\n");
      out.write("			</div>\n");
      out.write("			<br>\n");
      out.write("			<button type=\"submit\" class=\"btn btn-outline-primary\">등록</button>\n");
      out.write("		</form>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
